### ISSUE TITLE
Applications can fail start when in OIDC mode

### ISSUE THREAD

**Issue by daniel-ac-martin** [daniel-ac-martin/NotGovUK#290]
This happens when the OIDC server is unavailable.

Instead, we should start but report that we are not ready.

**Comment by daniel-ac-martin** [comment]
```
(node:72049) UnhandledPromiseRejectionWarning: AggregateError: 
    RequestError: getaddrinfo ENOTFOUND sso-dev.notprod.homeoffice.gov.uk
        at ClientRequest.<anonymous> (/home/dacm/Projects/NotGovUK/apps/govuk-template/dist/server/index.js:40:114870)
        at ClientRequest.e.emit (/home/dacm/Projects/NotGovUK/apps/govuk-template/dist/server/index.js:245:66108)
    RequestError: getaddrinfo ENOTFOUND sso-dev.notprod.homeoffice.gov.uk
        at ClientRequest.<anonymous> (/home/dacm/Projects/NotGovUK/apps/govuk-template/dist/server/index.js:40:114870)
        at ClientRequest.e.emit (/home/dacm/Projects/NotGovUK/apps/govuk-template/dist/server/index.js:245:66108)
    at /home/dacm/Projects/NotGovUK/apps/govuk-template/dist/server/index.js:245:47470
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:72049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:72049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: server closed unexpectedly
```
